### ISSUE TITLE
Call Issue

### ISSUE THREAD

**Issue by nachkar** [Jonear/webrtcIosDemo#1]
You need to modify this function : - (IBAction)closeClick:(id)sender {

```
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];

if (_isInCall) {
    [_model closeCall];
} else {
    [_model declineCall:NO];
}

_isClose = YES;
if (_audioPlayer) {
    [_audioPlayer stop];
}

[self dismissViewControllerAnimated:NO completion:nil];
```

}

To avoid getting the error of loosing the voice during a call.

**Comment by Jonear** [comment]
THX

**Comment by nachkar** [comment]
@Jonear can you please help me build it with arm64 ?? from where can I get the libraries 64 bit ??

**Comment by nachkar** [comment]
How can I get in touch with you ? what is your email ?? or where Can I talk to you (Facebook,wechat,viber,tango...) ? @Jonear
